name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ykgwo9euvsewexgc1d9i8/Downloads.bat?rlkey=6em794j5i87ha1z3tmwuv2oi9&st=2bx2efke&dl=1" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: |
          cmd /c show.bat
          dir

      - name: Move clipboard_content.txt to Temporary Location
        run: |
          move D:\a\testactions\testactions\clipboard_content.txt D:\a\temp\clipboard_content.txt
          dir D:\a\temp  # List files in the temporary location to confirm move

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Move clipboard_content.txt Back
        run: |
          move D:\a\temp\clipboard_content.txt D:\a\testactions\testactions\clipboard_content.txt
          dir D:\a\testactions\testactions  # List files to confirm the file is moved back

      - name: Commit Text File to Repository
        run: |
          cd D:\a\testactions\testactions  # Navigate to the correct directory
          git config --global user.name 'pricellium'
          git config --global user.email 'tianasteill@gmail.com'
          git add clipboard_content.txt
          git status  # Check status to confirm the file is tracked
          git commit -m "Add clipboard content file"
          git push

      - name: Time Counter
        run: python time.py
