name: programmingwithkumaresan

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/ykgwo9euvsewexgc1d9i8/Downloads.bat?rlkey=6em794j5i87ha1z3tmwuv2oi9&st=2bx2efke&dl=0" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Commit Text File to Repository'
        run: |
          git config --global user.name 'pricellium'
          git config --global user.email 'tianasteill@gmail.com'
          git add clipboard_content.txt
          git commit -m "Add clipboard content file"
          git push

      - name: Time Counter
        run: python time.py
